server {
    listen 80;

    # Serve os ficheiros estáticos do front-end (HTML/CSS/JS)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Reencaminha todos os pedidos que comecem por /api/ para o back-end Node.js
    location /api/ {
        proxy_pass http://propelada_api:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}